/* ------------------------------------------------------------------ */
/*      item            : ControlEvent.hxx
        generated by    : matteo (matteo)
        date            : Mon 04 Apr 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef ControlEvent_hxx
#define ControlEvent_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated ControlEvent.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/** not all these options are implemented
    powers are between 0 and 1
    angles in degrees
    */
struct ControlEvent
{
  /** typedef for internal reference */
  typedef ControlEvent __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  int id;

  /** ailerons */
  float aileron_power;

  /** A class member */
  float aileron_power_time;

  /** A class member */
  float aileron_offset;

  /** A class member */
  float aileron_offset_time;

  /** rudder */
  float rudder_power;

  /** A class member */
  float rudder_power_time;

  /** A class member */
  float rudder_offset;

  /** A class member */
  float rudder_offset_time;

  /** A class member */
  float rudder_bias;

  /** gear */
  int display_lg_failure;

  /** (bool gear_fail)
      aileron-rudder-interconnect */
  float ARI;

  /** elevator */
  float elevator_fix;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  ControlEvent();

  /** Constructor with arguments */
  ControlEvent(
        const int& id,
        const float& aileron_power,
        const float& aileron_power_time,
        const float& aileron_offset,
        const float& aileron_offset_time,
        const float& rudder_power,
        const float& rudder_power_time,
        const float& rudder_offset,
        const float& rudder_offset_time,
        const float& rudder_bias,
        const int& display_lg_failure,
        const float& ARI,
        const float& elevator_fix);

  /** copy constructor. */
  ControlEvent(const ControlEvent& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an ControlEvent from amorphous storage. */
  ControlEvent(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~ControlEvent();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, ControlEvent*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the ControlEvent into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the ControlEvent into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const ControlEvent& ref) const;

  /** unpacks the ControlEvent from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for ControlEvent
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const ControlEvent& o) const;

  /** Test for inequality. */
  inline bool operator != (const ControlEvent& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  ControlEvent& operator=(const ControlEvent& o);

  /** prints the ControlEvent to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const ControlEvent& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const ControlEvent& o,
                         const ControlEvent& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       ControlEvent& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           ControlEvent& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const ControlEvent& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    ControlEvent is ever used inside other dco objects. */
template <>
struct dco_nested<ControlEvent> : public dco_isnested { };
};
#endif


#endif
