/* ------------------------------------------------------------------ */
/*      item            : INCOSelect.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef INCOSelect_hxx
#define INCOSelect_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated INCOSelect.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>

#include <stringoptions.h>


/** An automatically generated class
    */
struct INCOSelect
{
  /** typedef for internal reference */
  typedef INCOSelect __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  int id;

  /** A class member */
  vstring name;

  /** A class member */
  vstring note;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  INCOSelect();

  /** Constructor with arguments */
  INCOSelect(
        const int& id,
        const vstring& name,
        const vstring& note);

  /** copy constructor. */
  INCOSelect(const INCOSelect& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an INCOSelect from amorphous storage. */
  INCOSelect(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~INCOSelect();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, INCOSelect*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the INCOSelect into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the INCOSelect into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const INCOSelect& ref) const;

  /** unpacks the INCOSelect from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for INCOSelect
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const INCOSelect& o) const;

  /** Test for inequality. */
  inline bool operator != (const INCOSelect& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  INCOSelect& operator=(const INCOSelect& o);

  /** prints the INCOSelect to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const INCOSelect& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const INCOSelect& o,
                         const INCOSelect& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       INCOSelect& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           INCOSelect& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const INCOSelect& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    INCOSelect is ever used inside other dco objects. */
template <>
struct dco_nested<INCOSelect> : public dco_isnested { };
};
#endif


#endif
