/* ------------------------------------------------------------------ */
/*      item            : AudioObjectMotion.hxx
        generated by    : matteo (matteo)
        date            : Wed 15 Dec 2021
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
        item            : AudioObjectMotion.dco
        made by         : Rene' van Paassen
        date            : 171130
        description     : Volume and pitch of an audio object
        copyright       : (c) 2017 TUDelft-AE-C&S
*/

#ifndef AudioObjectMotion_hxx
#define AudioObjectMotion_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated AudioObjectMotion.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>

#include "BaseObjectMotion.hxx"
#ifdef DUECA_CONFIG_HDF5
#include <H5Cpp.h>
#include <hdf5utils/HDF5DCOMetaFunctor.hxx>
#endif


/** This provides basic audio properties of a moving sound. The movement may
    be relative to the observer or absolute in the world, this
    distinction is made at creation
    */
struct AudioObjectMotion : public BaseObjectMotion
{
  /** typedef for internal reference */
  typedef AudioObjectMotion __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** volume of the playback */
  float volume;

  /** pitch value of the playback */
  float pitch;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  AudioObjectMotion();

  /** Constructor with arguments */
  AudioObjectMotion(
        const BaseObjectMotion& parent_BaseObjectMotion,
        const float& volume,
        const float& pitch);

  /** Constructor with all single (non-iterable) arguments */
  AudioObjectMotion(
        const float& volume,
        const float& pitch);

  /** copy constructor. */
  AudioObjectMotion(const AudioObjectMotion& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an AudioObjectMotion from amorphous storage. */
  AudioObjectMotion(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~AudioObjectMotion();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, AudioObjectMotion*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the AudioObjectMotion into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the AudioObjectMotion into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const AudioObjectMotion& ref) const;

  /** unpacks the AudioObjectMotion from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for AudioObjectMotion
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const AudioObjectMotion& o) const;

  /** Test for inequality. */
  inline bool operator != (const AudioObjectMotion& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  AudioObjectMotion& operator=(const AudioObjectMotion& o);

  /** prints the AudioObjectMotion to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const AudioObjectMotion& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const AudioObjectMotion& o,
                         const AudioObjectMotion& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       AudioObjectMotion& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           AudioObjectMotion& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const AudioObjectMotion& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    AudioObjectMotion is ever used inside other dco objects. */
template <>
struct dco_nested<AudioObjectMotion> : public dco_isnested { };
};
#endif

#if defined(DUECA_CONFIG_HDF5)
// functors guarded in a separate namespace
namespace AudioObjectMotion_space {

  // writes to file, reading from channel
  class HDF5DCOWriteFunctor: public dueca::hdf5log::HDF5DCOWriteFunctor
  {
    AudioObjectMotion example;
    BaseObjectMotion_space::HDF5DCOWriteFunctor __parent__;
  public:
    // constructor, to be invoked by the metafunctor
    HDF5DCOWriteFunctor(boost::weak_ptr<H5::H5File> file,
                        const std::string& path,
                        size_t chunksize,
                        const std::string& label,
                        bool compress, bool writeticks,
                        const dueca::DataTimeSpec* startend);

    // the functor member used by channel reading code
    bool operator() (const void* dpointer, const dueca::DataTimeSpec& ts);
  };

  // reads from file, writing to channel
  class HDF5DCOReadFunctor: public dueca::hdf5log::HDF5DCOReadFunctor
  {
    AudioObjectMotion example;
    BaseObjectMotion_space::HDF5DCOReadFunctor __parent__;
  public:
    // constructor, to be invoked by the metafunctor
    HDF5DCOReadFunctor(boost::weak_ptr<H5::H5File> file,
                       const std::string& path,
                       bool readticks);
    // the functor member used by channel writing code
    bool operator() (void* dpointer);
  };
} // end namespace AudioObjectMotion_space
#endif


#endif
