/* ------------------------------------------------------------------ */
/*      item            : BaseObjectPosition.hxx
        generated by    : matteo (matteo)
        date            : Wed 15 Dec 2021
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
        item            : BaseObjectPosition.dco
        made by         : Rene' van Paassen
        date            : 171119
        description     : Describes position and attitude of object in 3d space
        copyright       : (c) 2017 TUDelft-AE-C&S
*/

#ifndef BaseObjectPosition_hxx
#define BaseObjectPosition_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated BaseObjectPosition.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>

#include <fixvector.hxx>
#include <fixvector.hxx>
#ifdef DUECA_CONFIG_HDF5
#include <H5Cpp.h>
#include <hdf5utils/HDF5DCOMetaFunctor.hxx>
#endif


/** This provides the movement of an object, and the first derivative of that
    the class has a simple extrapolation method (extrapolate), that provides
    an object with extrapolated position. 
    */
struct BaseObjectPosition
{
  /** typedef for internal reference */
  typedef BaseObjectPosition __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** attitude of the object wrt the earth-fixed system, given as a 
      quaternion. The first parameter is the cosine parameter */
  dueca::fixvector<4,double> attitude_q;

  /** position of the object in an earth-fixed coordinate system
      double, since it might be an ECEF system */
  dueca::fixvector<3,double> xyz;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  BaseObjectPosition();

  /** Constructor with arguments */
  BaseObjectPosition(
        const dueca::fixvector<4,double>& attitude_q,
        const dueca::fixvector<3,double>& xyz);

  /** copy constructor. */
  BaseObjectPosition(const BaseObjectPosition& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an BaseObjectPosition from amorphous storage. */
  BaseObjectPosition(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~BaseObjectPosition();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, BaseObjectPosition*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the BaseObjectPosition into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the BaseObjectPosition into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const BaseObjectPosition& ref) const;

  /** unpacks the BaseObjectPosition from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for BaseObjectPosition
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const BaseObjectPosition& o) const;

  /** Test for inequality. */
  inline bool operator != (const BaseObjectPosition& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  BaseObjectPosition& operator=(const BaseObjectPosition& o);

  /** prints the BaseObjectPosition to a stream. */
  std::ostream & print(std::ostream& s) const;

// Additional custom code
#include "BaseObjectPositionExtra.hxx"
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const BaseObjectPosition& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const BaseObjectPosition& o,
                         const BaseObjectPosition& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       BaseObjectPosition& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           BaseObjectPosition& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const BaseObjectPosition& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    BaseObjectPosition is ever used inside other dco objects. */
template <>
struct dco_nested<BaseObjectPosition> : public dco_isnested { };
};
#endif

#if defined(DUECA_CONFIG_HDF5)
// functors guarded in a separate namespace
namespace BaseObjectPosition_space {

  // writes to file, reading from channel
  class HDF5DCOWriteFunctor: public dueca::hdf5log::HDF5DCOWriteFunctor
  {
    BaseObjectPosition example;
  public:
    // constructor, to be invoked by the metafunctor
    HDF5DCOWriteFunctor(boost::weak_ptr<H5::H5File> file,
                        const std::string& path,
                        size_t chunksize,
                        const std::string& label,
                        bool compress, bool writeticks,
                        const dueca::DataTimeSpec* startend);

    // the functor member used by channel reading code
    bool operator() (const void* dpointer, const dueca::DataTimeSpec& ts);
  };

  // reads from file, writing to channel
  class HDF5DCOReadFunctor: public dueca::hdf5log::HDF5DCOReadFunctor
  {
    BaseObjectPosition example;
  public:
    // constructor, to be invoked by the metafunctor
    HDF5DCOReadFunctor(boost::weak_ptr<H5::H5File> file,
                       const std::string& path,
                       bool readticks);
    // the functor member used by channel writing code
    bool operator() (void* dpointer);
  };
} // end namespace BaseObjectPosition_space
#endif


#endif
