/* ------------------------------------------------------------------ */
/*      item            : AutopilotTargets.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef AutopilotTargets_hxx
#define AutopilotTargets_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated AutopilotTargets.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/** An automatically generated class
    */
struct AutopilotTargets
{
  /** typedef for internal reference */
  typedef AutopilotTargets __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  double Vcmd;

  /** A class member */
  double Vx;

  /** A class member */
  double Vmin;

  /** A class member */
  double Vmax;

  /** A class member */
  double altitude;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  AutopilotTargets();

  /** Constructor with arguments */
  AutopilotTargets(
        const double& Vcmd,
        const double& Vx,
        const double& Vmin,
        const double& Vmax,
        const double& altitude);

  /** copy constructor. */
  AutopilotTargets(const AutopilotTargets& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an AutopilotTargets from amorphous storage. */
  AutopilotTargets(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~AutopilotTargets();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, AutopilotTargets*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the AutopilotTargets into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the AutopilotTargets into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const AutopilotTargets& ref) const;

  /** unpacks the AutopilotTargets from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for AutopilotTargets
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const AutopilotTargets& o) const;

  /** Test for inequality. */
  inline bool operator != (const AutopilotTargets& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  AutopilotTargets& operator=(const AutopilotTargets& o);

  /** prints the AutopilotTargets to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const AutopilotTargets& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const AutopilotTargets& o,
                         const AutopilotTargets& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       AutopilotTargets& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           AutopilotTargets& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const AutopilotTargets& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    AutopilotTargets is ever used inside other dco objects. */
template <>
struct dco_nested<AutopilotTargets> : public dco_isnested { };
};
#endif


#endif
