/* ------------------------------------------------------------------ */
/*      item            : MotionConfiguration.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef MotionConfiguration_hxx
#define MotionConfiguration_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated MotionConfiguration.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/**configuration of motion system
   FROM ExperimentControl/MotionConfigurator
   TO MotionLimiter
          motion: motion filter active
          filter: coarse configuration, id of filter (from add-motion-filter)
          param: fine configuration, id of parameterset (passed on to MF if != -1)
    */
struct MotionConfiguration
{
  /** typedef for internal reference */
  typedef MotionConfiguration __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** Enumerated type for an automatically generated object class */
  enum evt_type {
    Request,
    Confirm
  };

  /** A class member */
  evt_type event_type;

  /** A class member */
  bool motion;

  /** A class member */
  int filter;

  /** A class member */
  int param;

  /** for Confirm */
  bool filter_confirmed;

  /** A class member */
  bool param_confirmed;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  MotionConfiguration();

  /** Constructor with arguments */
  MotionConfiguration(
        const evt_type& event_type,
        const bool& motion,
        const int& filter,
        const int& param,
        const bool& filter_confirmed,
        const bool& param_confirmed);

  /** copy constructor. */
  MotionConfiguration(const MotionConfiguration& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an MotionConfiguration from amorphous storage. */
  MotionConfiguration(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~MotionConfiguration();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, MotionConfiguration*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the MotionConfiguration into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the MotionConfiguration into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const MotionConfiguration& ref) const;

  /** unpacks the MotionConfiguration from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for MotionConfiguration
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const MotionConfiguration& o) const;

  /** Test for inequality. */
  inline bool operator != (const MotionConfiguration& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  MotionConfiguration& operator=(const MotionConfiguration& o);

  /** prints the MotionConfiguration to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const MotionConfiguration& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const MotionConfiguration& o,
                         const MotionConfiguration& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       MotionConfiguration& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           MotionConfiguration& o)
{ o.unPackDataDiff(s); }
#endif

const char* const getString(const MotionConfiguration::evt_type &o);
void readFromString(MotionConfiguration::evt_type &o, const std::string& s);
#if !defined(__DCO_NOPACK)
void packData(::dueca::AmorphStore& s,
              const MotionConfiguration::evt_type &o);
void unPackData(::dueca::AmorphReStore& s,
                MotionConfiguration::evt_type &o);
#endif
namespace dueca {
  template <>
  const char* getclassname<MotionConfiguration::evt_type>();
};

PRINT_NS_START;
inline std::ostream&
operator << (std::ostream& s, const MotionConfiguration::evt_type& o)
{ return s << getString(o); }
inline std::istream&
operator >> (std::istream& s, MotionConfiguration::evt_type& o)
{ std::string tmp; s >> tmp; readFromString(o, tmp); return s; }
PRINT_NS_END;

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const MotionConfiguration& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    MotionConfiguration is ever used inside other dco objects. */
template <>
struct dco_nested<MotionConfiguration> : public dco_isnested { };
template <>
struct dco_nested< MotionConfiguration::evt_type > : public dco_isenum { };
};
#endif


#endif
