/* ------------------------------------------------------------------ */
/*      item            : MotionFilterUserData.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef MotionFilterUserData_hxx
#define MotionFilterUserData_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated MotionFilterUserData.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>

#include <fixvector.hxx>


/** An automatically generated class
    */
struct MotionFilterUserData
{
  /** typedef for internal reference */
  typedef MotionFilterUserData __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  dueca::fixvector<6,double> data;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  MotionFilterUserData();

  /** Constructor with arguments */
  MotionFilterUserData(
        const dueca::fixvector<6,double>& data);

  /** copy constructor. */
  MotionFilterUserData(const MotionFilterUserData& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an MotionFilterUserData from amorphous storage. */
  MotionFilterUserData(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~MotionFilterUserData();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, MotionFilterUserData*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the MotionFilterUserData into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the MotionFilterUserData into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const MotionFilterUserData& ref) const;

  /** unpacks the MotionFilterUserData from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for MotionFilterUserData
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const MotionFilterUserData& o) const;

  /** Test for inequality. */
  inline bool operator != (const MotionFilterUserData& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  MotionFilterUserData& operator=(const MotionFilterUserData& o);

  /** prints the MotionFilterUserData to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const MotionFilterUserData& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const MotionFilterUserData& o,
                         const MotionFilterUserData& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       MotionFilterUserData& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           MotionFilterUserData& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const MotionFilterUserData& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    MotionFilterUserData is ever used inside other dco objects. */
template <>
struct dco_nested<MotionFilterUserData> : public dco_isnested { };
};
#endif


#endif
