/* ------------------------------------------------------------------ */
/*      item            : CitationPilotInput.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef CitationPilotInput_hxx
#define CitationPilotInput_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated CitationPilotInput.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/** An automatically generated class
    */
struct CitationPilotInput
{
  /** typedef for internal reference */
  typedef CitationPilotInput __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** primary controls */
  float de;

  /** A class member */
  float da;

  /** A class member */
  float dr;

  /** secondary controls */
  float df;

  /** A class member */
  float pla1;

  /** A class member */
  float pla2;

  /** primary switches (pitch trim)
      handled by FCSAdapter, included in de
      secondary switches */
  float gear;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  CitationPilotInput();

  /** Constructor with arguments */
  CitationPilotInput(
        const float& de,
        const float& da,
        const float& dr,
        const float& df,
        const float& pla1,
        const float& pla2,
        const float& gear);

  /** copy constructor. */
  CitationPilotInput(const CitationPilotInput& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an CitationPilotInput from amorphous storage. */
  CitationPilotInput(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~CitationPilotInput();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, CitationPilotInput*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the CitationPilotInput into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the CitationPilotInput into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const CitationPilotInput& ref) const;

  /** unpacks the CitationPilotInput from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for CitationPilotInput
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const CitationPilotInput& o) const;

  /** Test for inequality. */
  inline bool operator != (const CitationPilotInput& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  CitationPilotInput& operator=(const CitationPilotInput& o);

  /** prints the CitationPilotInput to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const CitationPilotInput& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const CitationPilotInput& o,
                         const CitationPilotInput& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       CitationPilotInput& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           CitationPilotInput& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const CitationPilotInput& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    CitationPilotInput is ever used inside other dco objects. */
template <>
struct dco_nested<CitationPilotInput> : public dco_isnested { };
};
#endif


#endif
