/* ------------------------------------------------------------------ */
/*      item            : ManifoldChannel.hxx
        generated by    : matteo (matteo)
        date            : Wed 15 Dec 2021
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef ManifoldChannel_hxx
#define ManifoldChannel_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated ManifoldChannel.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/** An automatically generated class
    */
struct ManifoldChannel
{
  /** typedef for internal reference */
  typedef ManifoldChannel __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  float map_l;

  /** A class member */
  float map_r;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  ManifoldChannel();

  /** Constructor with arguments */
  ManifoldChannel(
        const float& map_l,
        const float& map_r);

  /** copy constructor. */
  ManifoldChannel(const ManifoldChannel& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an ManifoldChannel from amorphous storage. */
  ManifoldChannel(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~ManifoldChannel();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, ManifoldChannel*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the ManifoldChannel into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the ManifoldChannel into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const ManifoldChannel& ref) const;

  /** unpacks the ManifoldChannel from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for ManifoldChannel
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const ManifoldChannel& o) const;

  /** Test for inequality. */
  inline bool operator != (const ManifoldChannel& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  ManifoldChannel& operator=(const ManifoldChannel& o);

  /** prints the ManifoldChannel to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const ManifoldChannel& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const ManifoldChannel& o,
                         const ManifoldChannel& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       ManifoldChannel& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           ManifoldChannel& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const ManifoldChannel& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    ManifoldChannel is ever used inside other dco objects. */
template <>
struct dco_nested<ManifoldChannel> : public dco_isnested { };
};
#endif


#endif
