/* ------------------------------------------------------------------ */
/*      item            : Vc_Channel.hxx
        generated by    : matteo (matteo)
        date            : Thu 24 Mar 2022
        category        : header file
        description     : DUECA Communication Object (DCO)
                          automatically generated by dueca-codegen
        codegen version : 110
        language        : C++
*/

#ifndef Vc_Channel_hxx
#define Vc_Channel_hxx

#include <inttypes.h>

#if !defined(__DCO_NOPACK)
namespace dueca {
class AmorphStore;
class AmorphReStore;
struct DataWriterArraySize;
};
#endif
#if !defined(__DCO_STANDALONE)
namespace dueca {
struct CommObjectDataTable;
};
#include <gencodegen.h>
#if GENCODEGEN != 110
#error "Generated Vc_Channel.hxx too old, please clean with 'make mrproper'"
#endif
#include <CommObjectTraits.hxx>
#endif
#include <iostream>




/** An automatically generated class
    */
struct Vc_Channel
{
  /** typedef for internal reference */
  typedef Vc_Channel __ThisDCOType__;

public:
  /** The name of this class. */
  static const char* const classname;


  /** A class member */
  bool Threshold;

  /** A class member */
  bool Reduce_left;

  /** A class member */
  bool Reduce_right;

  /** A class member */
  float Vc_1;

  /** A class member */
  float Vc_2;

  /** A class member */
  int Threshold_param;

public:
  /** a "magic" number, hashed out of the class definition,
      that will be used to check consistency of the sent objects
      across the dueca nodes. */
  static const uint32_t magic_check_number;

  /** default constructor. */
  Vc_Channel();

  /** Constructor with arguments */
  Vc_Channel(
        const bool& Threshold,
        const bool& Reduce_left,
        const bool& Reduce_right,
        const float& Vc_1,
        const float& Vc_2,
        const int& Threshold_param);

  /** copy constructor. */
  Vc_Channel(const Vc_Channel& o);

#if !defined(__DCO_NOPACK)
  /** constructor to restore an Vc_Channel from amorphous storage. */
  Vc_Channel(dueca::AmorphReStore& r);
#endif

  /** destructor. */
  ~Vc_Channel();

#if !defined(__DCO_STANDALONE)
  /** new operator "new", which places objects not on a
      heap, but in one of the memory arenas. This to speed up
      memory management. */
  static void* operator new(size_t size);

  /** new operator "delete", to go with the new version
      of operator new. */
  static void operator delete(void* p);

  /** placement "new", needed for stl. */
  inline static void* operator new(size_t size, Vc_Channel*& o)
  { return reinterpret_cast<void*>(o); }
#endif

#if !defined(__DCO_NOPACK)
  /** packs the Vc_Channel into amorphous storage. */
  void packData(::dueca::AmorphStore& s) const;

  /** packs the Vc_Channel into amorphous storage.
      only differences with a previous object are packed. */
  void packDataDiff(::dueca::AmorphStore& s, const Vc_Channel& ref) const;

  /** unpacks the Vc_Channel from an amorphous storage. */
  void unPackData(::dueca::AmorphReStore& s);

  /** unpacks the differences for Vc_Channel
      from an amorphous storage. */
  void unPackDataDiff(::dueca::AmorphReStore& s);
#endif

  /** Test for equality. */
  bool operator == (const Vc_Channel& o) const;

  /** Test for inequality. */
  inline bool operator != (const Vc_Channel& o) const
  { return !(*this == o); }

  /** Assignment operator. */
  Vc_Channel& operator=(const Vc_Channel& o);

  /** prints the Vc_Channel to a stream. */
  std::ostream & print(std::ostream& s) const;
};

#if !defined(__DCO_NOPACK)
/** pack the object into amorphous storage. */
inline void packData(::dueca::AmorphStore& s,
                     const Vc_Channel& o)
{ o.packData(s); }

/** pack the differences between this object and another
    into amorphous storage. */
inline void packDataDiff(dueca::AmorphStore& s,
                         const Vc_Channel& o,
                         const Vc_Channel& ref)
{ o.packDataDiff(s, ref); }

/** unpack the object from amorphous storage. */
inline void unPackData(::dueca::AmorphReStore& s,
                       Vc_Channel& o)
{ o.unPackData(s); }

/** unpack the differences to this object from storage. */
inline void unPackDataDiff(dueca::AmorphReStore& s,
                           Vc_Channel& o)
{ o.unPackDataDiff(s); }
#endif

namespace std {
/** print to a stream. */
inline std::ostream &
operator << (std::ostream& s, const Vc_Channel& o)
{ return o.print(s); }
};

#if !defined(__DCO_STANDALONE)
namespace dueca {
/** Template specialization, defines a trait that is needed if
    Vc_Channel is ever used inside other dco objects. */
template <>
struct dco_nested<Vc_Channel> : public dco_isnested { };
};
#endif


#endif
